language: node_js
node_js:
- '5'
addons:
  code_climate:
    repo_token: <REPO TOKEN GOES HERE>
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: EpSYT34Yd7tsAmZO+c0fjCvEjFaTlLhX+IQG8+Rg/9+CjLhrkXRVG1vvQWNsbhBzyF9hvS5BT5G4dHjxjiXNZPmYQmnw6crVm+HCTyyxENcPijaZEfNgBBzj1FsaYVIWCvglF2eOYLWFenHdETB6VECuHwMonSttNb5WIkaY1p3HWe/Fd0mPIeAUVTurzyRxucocZioWOgsl+9xCHkY8uuEsBBmZwXz6atF8I1HEbGTT2qsJIMIISErFhh981vX+PzTPnFOj+/1aJvVi1YFMZzg9hNfl4C5FVt9K7aDoC/vmCGwsQbT+5mqgW8pHZhLRVzS3KOXq00Vri6aEpHaV0aFzd5GS+hxGU5VrlPV8AFVdS1/H1ZMlzGjWEx+25kfpsz6VqsgP+Mcidk8TyKwOOBgDvx1ic7L/bDWjv3xNxbeiH8oSl+XIV3cywsnq1l7IMEJRaGGk6SQCvWKP7Mbmlx9uB0MyNst0KLXklohWQOUoPcjwx4FtH/bL8x446l8aqQT+DEei26neNxU+oyxzPnR3Kzf9EzTvO+u7dkdte38Ttbx+hU3oQEQJpj9Cv4Xy90eOF2R8fmzYrslTTzTpHkeRE6md1ywm6d74+9/3+McPVU9FZEwnp4n6H2p4Yr7GGSWJbUUxmof6AQnI+fLHu23K/SYcWzBcuABOd4Krxr4=
  on:
    tags: true
    branches: true
